// Generated by CoffeeScript 1.9.1
(function() {
  var html, project, project_title, ref, section, section_link, section_title;

  window.research = {
    "Writing": {
      "Two Kinds of Demand": {
        img: "img/slots.jpeg",
        url: "https://medium.com/@edelwax/two-kinds-of-demand-a36c54b97ee1",
        readtime: '2 min',
        desc: "Is our economy powered by activities (and pageviews) we later regret?"
      },
      "Winning the Platform Wars with Morality": {
        url: "https://medium.com/@edelwax/mobile-platforms-and-human-values-74e5380713eb",
        readtime: '2 min',
        desc: "Design is no longer enough for your customers; the next decade is about values-alignment"
      },
      "Every Screen Empowers Us or Weakens Us": {
        img: "img/walle.jpeg",
        url: "https://medium.com/@edelwax/every-screenful-of-every-app-either-empowers-us-or-weakens-us-2ef22a472b30",
        readtime: '4 min',
        desc: "We make a thousand choices a day, and the character of those choices is in the end who we become."
      },
      "Deep Optimism": {
        url: "https://medium.com/@edelwax/deep-optimism-ba527ef817bb",
        readtime: '1 min',
        desc: "Ask them how the world works, or what can be improved—deep optimists will not answer quickly."
      }
    }
  };

  html = [];

  ref = window.research;
  for (section_title in ref) {
    section = ref[section_title];
    section_link = section_title.toLowerCase().replace(/\ /g, '-');
    html.push("<a id='" + section_link + "'/><section class='screenful'><h3>" + section_title + "</h3><div class='list'>");
    for (project_title in section) {
      project = section[project_title];
      if (project.url) {
        html.push("<a href='" + project.url + "'>");
      }
      html.push("<div class='researchItem'>");
      html.push("<div><div class='title'>" + project_title);
      if (project.readtime) {
        html.push("<span class='readtime'>" + project.readtime + " read</span>");
      }
      html.push("</div>");
      if (project.desc) {
        html.push("<div class='desc'>" + project.desc);
        if (project.tags) {
          html.push("<span class='tag'>" + project.tags + "</span>");
        }
        html.push("</div>");
      }
      html.push("</div>");
      if (project.img) {
        html.push("<img src='../" + project.img + "'>");
      }
      html.push("</div>");
      if (project.url) {
        html.push("</a>");
      }
    }
    html.push("</div></section>");
  }

  document.write(html.join(''));

}).call(this);
